Repository oVirt/ovirt-release, pull requests merged in 2022-04, with the labels that each got.

#156 automation: update actions
  .github/workflows/check-patch.yml
  .github/workflows/repoclosure-44.yml
  .github/workflows/repoclosure-45.yml
  .github/workflows/repoclosure.yml
Labels: automation

#158 el9: include gluster-ansible-roles within node el9
  ovirt-release-host-node.spec.in
Labels: el9-stream

#166 oVirt Engine 4.5 requires enabling mod_auth_openidc
  .github/workflows/check-patch.yml
  .github/workflows/repoclosure-45.yml
  .github/workflows/repoclosure.yml
Labels: el8-stream

#179 4.5: el9: switch to released yoga
  .github/workflows/repoclosure-45.yml
Labels: el9-stream

#180 4.5: el9: use centos released yoga
  .github/workflows/repoclosure-45.yml
Labels: el9-stream

#184 build: bump for 4.5.0.1 async
  configure.ac
  ovirt-release-host-node.spec.in
Labels: el8-stream
